[package]
name = "typed-scad"
version = "0.1.0"
authors = ["wcaokaze <wcaokaze@gmail.com>"]
edition = "2021"

[dependencies]
anyhow = "1.0.58"
once_cell = "1.13.0"
rayon = "1.5.3"
thiserror = "1.0.31"
